---
abstract: 'MongoDB model class for Catalyst'
author:
  - 'Torsten Raudssus <torsten@raudssus.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-MongoDB
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.8
  MongoDB: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
